# Generated by Django 2.2.11 on 2020-05-07 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masterTaskId', models.IntegerField(blank=True)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('question', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('isOccupied', models.BooleanField(default=False)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
    ]
