# Generated by Django 2.2.11 on 2020-05-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_unittasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='consultant',
            new_name='user',
        ),
    ]
