# Generated by Django 2.2.11 on 2020-05-07 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200507_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unittasks',
            name='profile',
        ),
    ]
