# Generated by Django 2.2.11 on 2020-05-07 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_unittasks_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnitTasks',
        ),
    ]
