# Generated by Django 2.2.11 on 2020-05-07 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_unittasks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
