# Generated by Django 2.2.11 on 2020-05-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_role',
            field=models.CharField(choices=[('approver', 'APPROVER'), ('consultant', 'CONSULTANT')], default='consultant', max_length=30),
        ),
    ]
