# Generated by Django 2.2.11 on 2020-05-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200509_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_role',
            field=models.CharField(choices=[('Approver', 'APPROVER'), ('Consultant', 'CONSULTANT')], default='Consultant', max_length=30),
        ),
    ]
