# Generated by Django 2.2.11 on 2020-05-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=50)),
                ('question', models.TextField()),
                ('status', models.CharField(default='RECIEVED', max_length=30)),
            ],
        ),
    ]
