# Generated by Django 2.2.11 on 2020-05-07 16:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_mastertasks_isoccupied'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastertasks',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 7, 16, 9, 24, 237436, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='mastertasks',
            name='lastModifiedBy',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
