# Generated by Django 2.2.11 on 2020-05-07 16:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20200507_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastertasks',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 7, 16, 31, 48, 654812, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mastertasks',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
