# Generated by Django 2.2.11 on 2020-05-07 16:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20200507_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastertasks',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 7, 16, 32, 1, 203639, tzinfo=utc)),
        ),
    ]
