# Generated by Django 2.2.11 on 2020-05-07 19:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20200507_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastertasks',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mastertasks',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 7, 19, 30, 25, 842865, tzinfo=utc)),
        ),
    ]
