# Generated by Django 2.2.11 on 2020-05-08 09:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20200508_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastertasks',
            name='quest_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mastertasks',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 9, 44, 55, 226002, tzinfo=utc)),
        ),
    ]
