# Generated by Django 2.2.11 on 2020-05-08 15:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20200508_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastertasks',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 15, 57, 10, 578027, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mastertasks',
            name='quest_id',
            field=models.CharField(default='No Id', max_length=100),
        ),
    ]
