# Generated by Django 2.2.11 on 2020-05-09 08:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_auto_20200509_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastertasks',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 8, 45, 49, 638704, tzinfo=utc)),
        ),
    ]
