# Generated by Django 2.2.11 on 2020-05-09 11:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_auto_20200509_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mastertasks',
            old_name='lastModifiedBy',
            new_name='approvedBy',
        ),
        migrations.AddField(
            model_name='mastertasks',
            name='solvedBy',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='mastertasks',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 11, 0, 46, 958438, tzinfo=utc)),
        ),
    ]
